In [2]:
import numpy as np

In [5]:
a = np.ones((2,4))
a

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [6]:
a.shape

(2, 4)

In [7]:
a.dtype

dtype('float64')

In [8]:
a.size

8

In [9]:
a = np.arange(10)**3
a


array([  0,   1,   8,  27,  64, 125, 216, 343, 512, 729])

In [11]:
a[2]

np.int64(8)

In [13]:
a[2:5]

array([ 8, 27, 64])

In [14]:
# equivalent to a[0:6:2] = 1000;
# from start to position 6, exclusive, set every 2nd element to 1000
a[:6:2] = 1000

In [15]:
a

array([1000,    1, 1000,   27, 1000,  125,  216,  343,  512,  729])

In [16]:
a[::-1]  # reversed a

array([ 729,  512,  343,  216,  125, 1000,   27, 1000,    1, 1000])

In [17]:
for i in a:
    print(i**(1 / 3.))

9.999999999999998
1.0
9.999999999999998
2.9999999999999996
9.999999999999998
4.999999999999999
5.999999999999999
6.999999999999999
7.999999999999999
8.999999999999998
